// File generated by FlutterFire CLI.
// Note: This file should be recreated by running 'flutterfire configure'
// For now, we're adding a placeholder file to allow the app to compile
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // In a real app, you would use 'flutterfire configure' to generate this file
    // For this demo, we'll use placeholder values
    return const FirebaseOptions(
      apiKey: "AIzaSyAbBIkZKdUUZr-Nm5I1UAM991fiZOm37eY",
      appId: "1:23646712593:android:dd9eb761430153e550d2b0",
      messagingSenderId: "23646712593",
      projectId: "project-st-iot",
      databaseURL: "https://project-st-iot-default-rtdb.firebaseio.com",
    );
  }
} 